# Generated by Django 2.0.7 on 2019-06-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacentre', '0002_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'Gender'},
        ),
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='datacentre.Gender'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='sex',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
